# Generated by Django 4.2.9 on 2024-01-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatData',
            fields=[
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID чата')),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чаты',
            },
        ),
    ]
