# Generated by Django 4.2.9 on 2024-01-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер')),
                ('name', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('price_in_rubles', models.PositiveIntegerField(verbose_name='Цена в рублях')),
                ('url_for_russians', models.URLField(blank=True, verbose_name='Url русского описания')),
            ],
            options={
                'verbose_name': 'впечатление',
                'verbose_name_plural': 'впечатления',
                'ordering': ['number'],
            },
        ),
    ]
