# Generated by Django 4.2.9 on 2024-01-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_botdata_options_botdata_payment_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botdata',
            name='payment_details',
        ),
        migrations.AddField(
            model_name='botdata',
            name='english_payment_details',
            field=models.TextField(blank=True, verbose_name='Реквизиты для оплаты сертификата (на английском)'),
        ),
        migrations.AddField(
            model_name='botdata',
            name='russian_payment_details',
            field=models.TextField(blank=True, verbose_name='Реквизиты для оплаты сертификата (на русском)'),
        ),
    ]
