# Generated by Django 4.2.9 on 2024-01-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_botdata_payment_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botdata',
            name='english_self_delivery_address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Адрес пункта самовывоза по-английски'),
        ),
        migrations.AddField(
            model_name='botdata',
            name='english_self_delivery_hours',
            field=models.CharField(blank=True, max_length=256, verbose_name='Время работы самовывоза по-английски'),
        ),
        migrations.AddField(
            model_name='botdata',
            name='russian_self_delivery_address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Адрес пункта самовывоза по-русски'),
        ),
        migrations.AddField(
            model_name='botdata',
            name='russian_self_delivery_hours',
            field=models.CharField(blank=True, max_length=256, verbose_name='Время работы самовывоза по-русски'),
        ),
    ]
